FROM docker.arvancloud.ir/node:20-alpine

WORKDIR /app

# Install OpenSSL 1.1.x compatibility libraries required by Prisma
RUN apk add --no-cache openssl libc6-compat

# Install Prisma CLI globally (optional, but ensures it's available)
RUN npm install -g prisma@5.22.0

# Default command
CMD ["sh", "-c", "npx prisma@5.22.0 generate && npx prisma@5.22.0 studio --port 5555 --hostname 0.0.0.0"]



